### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by skdhg** [skdhg/nobu#5]
- [x] Tabs
  - [x] Creating new tabs
  - [x] Closing tabs
  - [x] Switching between tabs
  - [x] Favicon
  - [x] Loading icon
- [x] Navigation
  - [x] History
    - [x] Back
    - [x] Forward
    - [x] Reload
  - [x] Address bar
- [ ] Context Menu
  - [x] Inspect
  - [x] History: back, forward, reload
  - [ ] Link
    - [x] Open in new tab
    - [ ] Open in new window
  - [ ] Text
    - [ ] Copy
  - [ ] Image
    - [ ] Copy
    - [ ] Copy Link
- [ ] Settings
  - [ ] Theme
  - [ ] Default search engine
- [ ] Menu bar
- [ ] Screen Utilities
  - [ ] Multi-Device emulation
  - [ ] Toggle features on/off

The list mentioned above may change anytime.
